AP_CFLAGS=`pkg-config alsaplayer --cflags`
AP_LIBS=`pkg-config alsaplayer --libs`

CC=gcc
CFLAGS=-Os -Wall -fomit-frame-pointer $(AP_CFLAGS)
LDFLAGS=$(AP_LIBS) -s

ap-control:

clean:
	rm -f ap-control

