#!/bin/sh
if [ -f src/interface.c ];then
	sed s/_with_mnemonic' ("")'/' ()'/ src/interface.c > src/interface.tmp
	mv src/interface.tmp ../interface.cpp
	cp -f src/support.c ../support.cpp
	cp -f src/support.h ../support.h
	echo fixup done...OK
else
	echo interface.cpp not found...ERROR
fi
