/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_root_window (void)
{
  GtkWidget *root_window;
  GtkWidget *root_box;
  GtkWidget *player_vbox;
  GtkWidget *player_box;
  GtkWidget *control_box;
  GtkWidget *core_box;
  GtkWidget *vbox6;
  GtkWidget *hbox4;
  GtkWidget *vbox7;
  GtkWidget *status_label;
  GtkWidget *hbox17;
  GtkWidget *vbox16;
  GtkWidget *format_label;
  GtkWidget *time_label;
  GtkWidget *hbox8;
  GtkWidget *pos_scale;
  GtkWidget *hbox3;
  GtkWidget *hbox2;
  GtkWidget *prev_button;
  GtkWidget *stop_button;
  GtkWidget *play_button;
  GtkWidget *next_button;
  GtkWidget *hbox5;
  GtkWidget *vbox9;
  GtkWidget *hbox6;
  GtkWidget *hbox7;
  GtkWidget *vbox11;
  GtkWidget *playlist_button;
  GtkWidget *vbox8;
  GtkWidget *vol_scale;

  root_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (root_window), _("AlsaPlayer"));

  root_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (root_box);
  gtk_container_add (GTK_CONTAINER (root_window), root_box);

  player_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (player_vbox);
  gtk_box_pack_start (GTK_BOX (root_box), player_vbox, TRUE, TRUE, 0);

  player_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (player_box);
  gtk_box_pack_start (GTK_BOX (player_vbox), player_box, FALSE, TRUE, 0);

  control_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (control_box);
  gtk_box_pack_start (GTK_BOX (player_box), control_box, FALSE, TRUE, 0);

  core_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (core_box);
  gtk_box_pack_start (GTK_BOX (control_box), core_box, FALSE, TRUE, 2);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (core_box), vbox6, TRUE, TRUE, 2);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox4, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox7, TRUE, TRUE, 0);

  status_label = gtk_label_new (_("Dit is text"));
  gtk_widget_show (status_label);
  gtk_box_pack_start (GTK_BOX (vbox7), status_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (status_label), 0, 0.5);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox17, FALSE, FALSE, 0);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (hbox17), vbox16, TRUE, TRUE, 0);

  format_label = gtk_label_new (_("Dit is text"));
  gtk_widget_show (format_label);
  gtk_box_pack_start (GTK_BOX (vbox16), format_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (format_label), 0, 0.5);

  time_label = gtk_label_new (_("Dit is ook text"));
  gtk_widget_show (time_label);
  gtk_box_pack_start (GTK_BOX (hbox17), time_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (time_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (time_label), 0, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (control_box), hbox8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 4);

  pos_scale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 0, 0, 0)));
  gtk_widget_show (pos_scale);
  gtk_box_pack_start (GTK_BOX (hbox8), pos_scale, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (pos_scale, GTK_CAN_FOCUS);
  gtk_scale_set_draw_value (GTK_SCALE (pos_scale), FALSE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (control_box), hbox3, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 4);

  prev_button = gtk_button_new ();
  gtk_widget_show (prev_button);
  gtk_box_pack_start (GTK_BOX (hbox2), prev_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (prev_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (prev_button, GTK_CAN_FOCUS);

  stop_button = gtk_button_new ();
  gtk_widget_show (stop_button);
  gtk_box_pack_start (GTK_BOX (hbox2), stop_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (stop_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (stop_button, GTK_CAN_FOCUS);

  play_button = gtk_button_new ();
  gtk_widget_show (play_button);
  gtk_box_pack_start (GTK_BOX (hbox2), play_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (play_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (play_button, GTK_CAN_FOCUS);

  next_button = gtk_button_new ();
  gtk_widget_show (next_button);
  gtk_box_pack_start (GTK_BOX (hbox2), next_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (next_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (next_button, GTK_CAN_FOCUS);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox5, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox9, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox6, TRUE, TRUE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (hbox6), hbox7, TRUE, TRUE, 0);

  vbox11 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox7), vbox11, FALSE, FALSE, 0);

  playlist_button = gtk_button_new ();
  gtk_widget_show (playlist_button);
  gtk_box_pack_start (GTK_BOX (vbox11), playlist_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (playlist_button, 58, 21);
  GTK_WIDGET_UNSET_FLAGS (playlist_button, GTK_CAN_FOCUS);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 6);

  vol_scale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (14, 0, 14, 0, 0, 0)));
  gtk_widget_show (vol_scale);
  gtk_box_pack_start (GTK_BOX (vbox8), vol_scale, TRUE, TRUE, 0);
  gtk_widget_set_size_request (vol_scale, 80, 15);
  GTK_WIDGET_UNSET_FLAGS (vol_scale, GTK_CAN_FOCUS);
  gtk_scale_set_draw_value (GTK_SCALE (vol_scale), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (root_window, root_window, "root_window");
  GLADE_HOOKUP_OBJECT (root_window, root_box, "root_box");
  GLADE_HOOKUP_OBJECT (root_window, player_vbox, "player_vbox");
  GLADE_HOOKUP_OBJECT (root_window, player_box, "player_box");
  GLADE_HOOKUP_OBJECT (root_window, control_box, "control_box");
  GLADE_HOOKUP_OBJECT (root_window, core_box, "core_box");
  GLADE_HOOKUP_OBJECT (root_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (root_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (root_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (root_window, status_label, "status_label");
  GLADE_HOOKUP_OBJECT (root_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (root_window, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (root_window, format_label, "format_label");
  GLADE_HOOKUP_OBJECT (root_window, time_label, "time_label");
  GLADE_HOOKUP_OBJECT (root_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (root_window, pos_scale, "pos_scale");
  GLADE_HOOKUP_OBJECT (root_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (root_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (root_window, prev_button, "prev_button");
  GLADE_HOOKUP_OBJECT (root_window, stop_button, "stop_button");
  GLADE_HOOKUP_OBJECT (root_window, play_button, "play_button");
  GLADE_HOOKUP_OBJECT (root_window, next_button, "next_button");
  GLADE_HOOKUP_OBJECT (root_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (root_window, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (root_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (root_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (root_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (root_window, playlist_button, "playlist_button");
  GLADE_HOOKUP_OBJECT (root_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (root_window, vol_scale, "vol_scale");

  return root_window;
}

GtkWidget*
create_playlist_window (void)
{
  GtkWidget *playlist_window;
  GtkWidget *vbox12;
  GtkWidget *hbox9;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *vbuttonbox1;
  GtkWidget *button9;
  GtkWidget *alignment1;
  GtkWidget *hbox10;
  GtkWidget *image1;
  GtkWidget *add_button;
  GtkWidget *button10;
  GtkWidget *alignment2;
  GtkWidget *hbox11;
  GtkWidget *image2;
  GtkWidget *remove_button;
  GtkWidget *shuffle_button;
  GtkWidget *load_button;
  GtkWidget *alignment6;
  GtkWidget *hbox15;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *save_button;
  GtkWidget *alignment7;
  GtkWidget *hbox16;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *vbox15;

  playlist_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (playlist_window), _("Playlist"));

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (playlist_window), vbox12);
  gtk_container_set_border_width (GTK_CONTAINER (vbox12), 4);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox9, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox9), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview1), TRUE);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox9), vbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox1), GTK_BUTTONBOX_START);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button9), alignment1);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox10);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox10), image1, FALSE, FALSE, 0);

  add_button = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (add_button);
  gtk_box_pack_start (GTK_BOX (hbox10), add_button, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button10), alignment2);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox11);

  image2 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox11), image2, FALSE, FALSE, 0);

  remove_button = gtk_label_new_with_mnemonic (_("Remove"));
  gtk_widget_show (remove_button);
  gtk_box_pack_start (GTK_BOX (hbox11), remove_button, FALSE, FALSE, 0);

  shuffle_button = gtk_button_new_with_mnemonic (_("Shuffle"));
  gtk_widget_show (shuffle_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), shuffle_button);
  GTK_WIDGET_SET_FLAGS (shuffle_button, GTK_CAN_DEFAULT);

  load_button = gtk_button_new ();
  gtk_widget_show (load_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), load_button);
  GTK_WIDGET_SET_FLAGS (load_button, GTK_CAN_DEFAULT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (load_button), alignment6);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox15);

  image6 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox15), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Load..."));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox15), label6, FALSE, FALSE, 0);

  save_button = gtk_button_new ();
  gtk_widget_show (save_button);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), save_button);
  GTK_WIDGET_SET_FLAGS (save_button, GTK_CAN_DEFAULT);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (save_button), alignment7);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox16);

  image7 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox16), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Save..."));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox16), label7, FALSE, FALSE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (vbox12), vbox15, FALSE, TRUE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (playlist_window, playlist_window, "playlist_window");
  GLADE_HOOKUP_OBJECT (playlist_window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (playlist_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (playlist_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (playlist_window, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (playlist_window, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (playlist_window, button9, "button9");
  GLADE_HOOKUP_OBJECT (playlist_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (playlist_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (playlist_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (playlist_window, add_button, "add_button");
  GLADE_HOOKUP_OBJECT (playlist_window, button10, "button10");
  GLADE_HOOKUP_OBJECT (playlist_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (playlist_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (playlist_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (playlist_window, remove_button, "remove_button");
  GLADE_HOOKUP_OBJECT (playlist_window, shuffle_button, "shuffle_button");
  GLADE_HOOKUP_OBJECT (playlist_window, load_button, "load_button");
  GLADE_HOOKUP_OBJECT (playlist_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (playlist_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (playlist_window, image6, "image6");
  GLADE_HOOKUP_OBJECT (playlist_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (playlist_window, save_button, "save_button");
  GLADE_HOOKUP_OBJECT (playlist_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (playlist_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (playlist_window, image7, "image7");
  GLADE_HOOKUP_OBJECT (playlist_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (playlist_window, vbox15, "vbox15");

  return playlist_window;
}

