/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_root_window (void)
{
  GtkWidget *root_window;
  GtkWidget *root_box;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *about1;
  GtkWidget *player_vbox;
  GtkWidget *player_box;
  GtkWidget *control_box;
  GtkWidget *core_box;
  GtkWidget *vbox6;
  GtkWidget *hbox4;
  GtkWidget *vbox7;
  GtkWidget *format_label;
  GtkWidget *vbox10;
  GtkWidget *time_label;
  GtkWidget *hbox8;
  GtkWidget *pos_scale;
  GtkWidget *hbox3;
  GtkWidget *hbox2;
  GtkWidget *prev_button;
  GtkWidget *stop_button;
  GtkWidget *play_button;
  GtkWidget *next_button;
  GtkWidget *hbox5;
  GtkWidget *vbox9;
  GtkWidget *hbox6;
  GtkWidget *hbox7;
  GtkWidget *vbox11;
  GtkWidget *playlist_button;
  GtkWidget *vbox8;
  GtkWidget *vol_scale;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  root_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (root_window), _("AlsaPlayer"));

  root_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (root_box);
  gtk_container_add (GTK_CONTAINER (root_window), root_box);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (root_box), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu1), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu1), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu1), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu1), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu1), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu2), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu2), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu2), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu2), delete1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu4), about1);

  player_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (player_vbox);
  gtk_box_pack_start (GTK_BOX (root_box), player_vbox, TRUE, TRUE, 0);

  player_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (player_box);
  gtk_box_pack_start (GTK_BOX (player_vbox), player_box, FALSE, TRUE, 0);

  control_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (control_box);
  gtk_box_pack_start (GTK_BOX (player_box), control_box, FALSE, TRUE, 0);

  core_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (core_box);
  gtk_box_pack_start (GTK_BOX (control_box), core_box, FALSE, TRUE, 2);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (core_box), vbox6, TRUE, TRUE, 2);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox4, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox7, TRUE, TRUE, 0);

  format_label = gtk_label_new ("");
  gtk_widget_show (format_label);
  gtk_box_pack_start (GTK_BOX (vbox7), format_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (format_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (format_label), 0, 0.5);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox10, FALSE, FALSE, 0);

  time_label = gtk_label_new ("");
  gtk_widget_show (time_label);
  gtk_box_pack_start (GTK_BOX (vbox10), time_label, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (time_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (time_label), 0, 0.5);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (control_box), hbox8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 4);

  pos_scale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 100, 0, 0, 0)));
  gtk_widget_show (pos_scale);
  gtk_box_pack_start (GTK_BOX (hbox8), pos_scale, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (pos_scale, GTK_CAN_FOCUS);
  gtk_scale_set_draw_value (GTK_SCALE (pos_scale), FALSE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (control_box), hbox3, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 4);

  prev_button = gtk_button_new ();
  gtk_widget_show (prev_button);
  gtk_box_pack_start (GTK_BOX (hbox2), prev_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (prev_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (prev_button, GTK_CAN_FOCUS);

  stop_button = gtk_button_new ();
  gtk_widget_show (stop_button);
  gtk_box_pack_start (GTK_BOX (hbox2), stop_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (stop_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (stop_button, GTK_CAN_FOCUS);

  play_button = gtk_button_new ();
  gtk_widget_show (play_button);
  gtk_box_pack_start (GTK_BOX (hbox2), play_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (play_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (play_button, GTK_CAN_FOCUS);

  next_button = gtk_button_new ();
  gtk_widget_show (next_button);
  gtk_box_pack_start (GTK_BOX (hbox2), next_button, FALSE, FALSE, 1);
  gtk_widget_set_size_request (next_button, 31, 21);
  GTK_WIDGET_UNSET_FLAGS (next_button, GTK_CAN_FOCUS);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox5, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox9, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox6, TRUE, TRUE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (hbox6), hbox7, TRUE, TRUE, 0);

  vbox11 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox7), vbox11, FALSE, FALSE, 0);

  playlist_button = gtk_button_new ();
  gtk_widget_show (playlist_button);
  gtk_box_pack_start (GTK_BOX (vbox11), playlist_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (playlist_button, 58, 21);
  GTK_WIDGET_UNSET_FLAGS (playlist_button, GTK_CAN_FOCUS);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 6);

  vol_scale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (14, 0, 14, 0, 0, 0)));
  gtk_widget_show (vol_scale);
  gtk_box_pack_start (GTK_BOX (vbox8), vol_scale, TRUE, TRUE, 0);
  gtk_widget_set_size_request (vol_scale, 80, 15);
  GTK_WIDGET_UNSET_FLAGS (vol_scale, GTK_CAN_FOCUS);
  gtk_scale_set_draw_value (GTK_SCALE (vol_scale), FALSE);

  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (root_window, root_window, "root_window");
  GLADE_HOOKUP_OBJECT (root_window, root_box, "root_box");
  GLADE_HOOKUP_OBJECT (root_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (root_window, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (root_window, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (root_window, new1, "new1");
  GLADE_HOOKUP_OBJECT (root_window, open1, "open1");
  GLADE_HOOKUP_OBJECT (root_window, save1, "save1");
  GLADE_HOOKUP_OBJECT (root_window, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (root_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (root_window, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (root_window, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (root_window, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (root_window, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (root_window, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (root_window, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (root_window, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (root_window, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (root_window, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (root_window, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (root_window, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (root_window, about1, "about1");
  GLADE_HOOKUP_OBJECT (root_window, player_vbox, "player_vbox");
  GLADE_HOOKUP_OBJECT (root_window, player_box, "player_box");
  GLADE_HOOKUP_OBJECT (root_window, control_box, "control_box");
  GLADE_HOOKUP_OBJECT (root_window, core_box, "core_box");
  GLADE_HOOKUP_OBJECT (root_window, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (root_window, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (root_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (root_window, format_label, "format_label");
  GLADE_HOOKUP_OBJECT (root_window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (root_window, time_label, "time_label");
  GLADE_HOOKUP_OBJECT (root_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (root_window, pos_scale, "pos_scale");
  GLADE_HOOKUP_OBJECT (root_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (root_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (root_window, prev_button, "prev_button");
  GLADE_HOOKUP_OBJECT (root_window, stop_button, "stop_button");
  GLADE_HOOKUP_OBJECT (root_window, play_button, "play_button");
  GLADE_HOOKUP_OBJECT (root_window, next_button, "next_button");
  GLADE_HOOKUP_OBJECT (root_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (root_window, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (root_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (root_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (root_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (root_window, playlist_button, "playlist_button");
  GLADE_HOOKUP_OBJECT (root_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (root_window, vol_scale, "vol_scale");

  gtk_window_add_accel_group (GTK_WINDOW (root_window), accel_group);

  return root_window;
}

