name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    runs:
    using: "composite"
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
            ref: 'release'

#      - name: Set up autotools
#        run: sudo apt-get install -y autoconf automake libtool intltool

#      - name: Run autogen.sh
#        run: ./autogen.sh

      - name: Run configure
        run: ./configure

      - name: Run make dist to create the archive
        run: make dist

      - name: Get the generated archive name
        id: get_dist_name
        run: echo "ARCHIVE_NAME=$(ls *.tar.gz)" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          asset_content_type: application/gzip
